TestProject/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.userSettings import views as user_views
from apps.navigation import views as nav_views

# CustomLoginView.as_view()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_views.custom_login, name='login'),
    path('register/', user_views.register_view, name='register'),
    path('home/', nav_views.index, name='home'),
    path('pack/', include('apps.packBench.urls', namespace='pack')),
]

apps/packBench/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from apps.packBench import views

urlpatterns = [
                  # path('pack_operations/', views.get_data, name='pack_operations'),
                  path('pack_operation/', views.PackOperationView.as_view(), name='pack_operation'),
                  path('ajax/load_code_branches/', views.LoadCodeBranches.as_view(), name='load_code_branches'),
                  path('pack_logs/', views.PackLogListView.as_view(), name='pack_log_list'),
                  # path('test/', views.pack_package_v, name='test'),
                  # path('get_task_result/', views.get_task_result, name='get_task_result'),
                  path('results/', views.GetTaskResult.as_view(), name='task-results')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'userSettings'

# celery -A TestProject beat -l info  # 启动beat任务调度器
# celery -A TestProject worker -P eventlet -l info  # 启动worker消费异步任务

apps/navigation/models.py
from django.db import models


# Create your models here.
class Permission(models.Model):
    # 权限表，用于控制url是否可访问
    pass
    path_name = models.CharField(verbose_name='路径名称', max_length=100, unique=True)
    url = models.URLField(verbose_name='url', max_length=200, unique=True)
    parent = models.ForeignKey('self', verbose_name='父级菜单', on_delete=models.CASCADE, null=True, blank=True)
    is_menu = models.BooleanField(verbose_name='是否为菜单', default=False)
    title = models.CharField(verbose_name='标题', max_length=100, unique=True)
    icon = models.ImageField(verbose_name='图标', upload_to='icon/', blank=True, null=True)
    status = models.BooleanField(verbose_name='状态', default=True)

apps/navigation/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'navigation/index.html')

apps/navigation/templates/navigation/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>导航</h1>
</body>
</html>

apps/navigation/templates/navigation/packBenchBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <script href="{% static 'bootstrap-5.3.0-alpha1-dist/js/bootstrap.bundle.min.js' %}" rel="stylesheet"></script>
    <link href="{% static 'Anchor-Bootstrap-UI-Kit/assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'Anchor-Bootstrap-UI-Kit/assets/css/vendor/aos.css' %}" rel="stylesheet"/>
    <link href="{% static 'private/a.css' %}" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {#    <title>{% block title %}默认标题{% endblock %}</title>#}
    <title>
        {% block title %}
            {% if request.resolver_match.url_name == 'pack_log_list' %}打包记录
            {% elif request.resolver_match.url_name == 'pack_operation' %}打包操作
            {% else %}DHC-自动化研发运维系统
            {% endif %}
        {% endblock %}
    </title>
    <!-- 引入 CSS 文件 -->
    {#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>
<body>
{% csrf_token %}
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="">
                <i class="fas fa-anchor mr-2"></i>
                <strong>DHC-</strong>自动化研发运维系统</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarNavDropdown-1"
                    aria-controls="navbarNavDropdown-1" aria-expanded="false" aria-label="Toggle navigation" style="">
                <span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown-1">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#待定1">Features</a></li>
                    <li class="nav-item"><a class="nav-link" href="#待定2">Pricing</a></li>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button"
                                                     id="navbarDropdownMenuLink" data-bs-toggle="dropdown"
                                                     aria-haspopup="true" aria-expanded="false">打包服务</a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'pack:pack_log_list' %}">打包记录</a></li>
                            <li><a class="dropdown-item" href="{% url 'pack:pack_operation' %}">打包操作</a></li>
                            <li><a class="dropdown-item" href="#待定3">Marketing</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#待定4">Separated link</a></li>

                        </ul>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pack:task-results' %}" data-bs-toggle="tooltip"
                           data-bs-placement="bottom"
                           data-tip="查询任务情况">
                            <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                                <path d="M11 2a9 9 0 1 0 5.618 16.032l3.675 3.675a1 1 0 0 0 1.414-1.414l-3.675-3.675A9 9 0 0 0 11 2zm0 16a7 7 0 1 1 0-14 7 7 0 0 1 0 14z"/>
                            </svg>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#待定5">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#待定6">
                            <i class="fab fa-facebook"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#待定7">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#待定8">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>


<div>
    <html>

    <main class="flex-grow-1">
        <head>
            {% block styles %}
                <!-- 样式内容 -->
            {% endblock %}
        </head>

        <body>
        {% block content %}
            <!-- 默认内容 -->
        {% endblock %}

        {% block scripts %}
            <!-- js -->
        {% endblock %}

        </body>
    </main>
    </html>
</div>

<div>
    <br>
    <br>
    <br>
    <br>
    <footer class="text-center py-3 mt-auto">
        <p class="mb-0">&copy; 2024 CICD研发运维一体化系统</p>
    </footer>
</div>
<script src="{% static 'bootstrap-5.3.0-alpha1-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'Anchor-Bootstrap-UI-Kit/assets/js/functions.js' %}"></script>
<script src="{% static 'Anchor-Bootstrap-UI-Kit/assets/js/vendor/aos.js' %}"></script>
<script>AOS.init();</script>  <!-- 初始化 AOS 动画 -->
<script>
    // 设置全局AJAX头部
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("csrftoken", "{{ csrf_token }}");
            }
        }
    });
</script>
</body>
</html>